name: Mypy Check

on:
  push:
    paths:
      - 'pronotepy/**.py'
    branches:
      - master
  workflow_dispatch:
    

jobs:
  run_mypy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install dev dependencies
        run: python -m pip install -r requirements.txt
      - name: Run mypy
        run: python -m mypy pronotepy --pretty --disallow-untyped-defs --disallow-incomplete-defs
